#!/usr/bin/env sh

module=${1-default}
env=${2-default}

echo "0. 在[$env]环境下启动应用[$module]"

cd "$module" || exit
echo "run jar $module at $(pwd)"
nohup java -jar "build/libs/$module-1.0.0-SNAPSHOT.jar" --spring.profiles.active="$env" &
