#!/bin/bash
set -e # terminate execution on command failure
olddb=${1-aum_store}
newdb=${2-aum_store_back}

echo "rename $olddb to $newdb"
mysqlconn="mysql -h 127.0.0.1 -u root -p12345678"
#$mysqlconn -e "CREATE DATABASE $newdb"
params=$($mysqlconn -N -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_schema='$olddb' and TABLE_TYPE='BASE TABLE'")
for name in $params; do
  echo "rename table $olddb.$name to $newdb.$name"
  $mysqlconn -e "RENAME TABLE $olddb.$name to $newdb.$name"
done
#$mysqlconn -e "DROP DATABASE $olddb"

# CREATE TABLE aum_detection.user like aum_detection1.user;
# insert into  aum_detection.user select * from aum_detection1.user;

