#!/bin/bash
set -e # terminate execution on command failure
olddb=${1-aum_store}
newdb=${2-aum_store_back}

echo "rename $olddb to $newdb"
mysqlconn="mysql -h 127.0.0.1 -u root -p12345678"
#$mysqlconn -e "CREATE DATABASE $newdb"
params=$($mysqlconn -N -e "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE table_schema='$olddb'")
for name in $params; do
  echo "copy table $newdb.$name from $olddb.$name"
  $mysqlconn -e "create table $newdb.$name select * from $olddb.$name"
done
#$mysqlconn -e "DROP DATABASE $olddb"

# CREATE TABLE aum_detection.user like aum_detection1.user;
# insert into  aum_detection.user select * from aum_detection1.user;

