= 磁盘

//@formatter:off

硬盘、软盘。

== lsblk

lsblk 是 [.underline]##l##i[.underline]##s##t [.underline]##bl##oc[.underline]##k## devices 的缩写，指列出块设备。

lsblk 列出了有关所有可用或指定块设备的信息。lsblk 命令读取 *sysfs* 文件系统以收集信息。

默认情况下，该命令以树状格式打印所有块设备（RAM 除外）。使用 `lsblk --help` 获取所有可用列的列表。

.lsblk
[source%nowrap,bash]
----
$ lsblk
NAME            MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda               8:0    0   30G  0 disk
├─sda1            8:1    0    1G  0 part /boot
└─sda2            8:2    0    7G  0 part
  ├─centos-root 253:0    0  6.2G  0 lvm  /
  └─centos-swap 253:1    0  820M  0 lvm  [SWAP]
sr0              11:0    1 1024M  0 rom
----

sda::
sd 是 [.underline]##S##CSI footnote:[https://en.wikipedia.org/wiki/SCSI[SCSI^] 是一套用于在计算机和外围设备之间进行物理连接和传输数据的标准。] [.underline]##d##isk 的缩写。
a 表示系统读取到的第一块硬盘，如果有多块硬盘，则从 a ~ z 依次排列。
sda1::
1 表示 sda 硬盘下的第一个分区，如果有多个分区，则从 1 ~ 9 依次排列。
sr0::
sr 是 [.underline]##S##CSI [.underline]##R##OM 的缩写，数字含义同上。
MAJ:MIN::
设备主次号。
RM::
RM 是 [.underline]##r##e[.underline]##m##ovable device 的缩写，表示是否可移除设备。
RO::
是否只读设备。
lvm::
参考 <<_lvm>>。

== fdisk

fdisk 是 [.underline]##f##ormat [.underline]#disk# 的缩写，指操作磁盘分区表。

.常用命令如下：
[source%nowrap,bash]
----
# 列出分区表
$ fdisk -l

Disk /dev/sda: 32.2 GB, 32212254720 bytes, 62914560 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000bf7e3

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048     2099199     1048576   83  Linux
/dev/sda2         2099200    16777215     7339008   8e  Linux LVM

Disk /dev/mapper/centos-root: 6652 MB, 6652166144 bytes, 12992512 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/centos-swap: 859 MB, 859832320 bytes, 1679360 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

# 更改分区表
$ fdisk /dev/sda
Command (m for help): m
Command action
   a   toggle a bootable flag
   b   edit bsd disklabel
   c   toggle the dos compatibility flag
   d   delete a partition
   g   create a new empty GPT partition table
   G   create an IRIX (SGI) partition table
   l   list known partition types
   m   print this menu
   n   add a new partition
   o   create a new empty DOS partition table
   p   print the partition table
   q   quit without saving changes
   s   create a new empty Sun disklabel
   t   change a partition\'s system id
   u   change display/entry units
   v   verify the partition table
   w   write table to disk and exit
   x   extra functionality (experts only)

Command (m for help): n
Partition type:
   p   primary (2 primary, 0 extended, 2 free)
   e   extended
Select (default p): p
Partition number (3,4, default 3):
Using default value 3
First sector (16777216-62914559, default 16777216):
Using default value 16777216
Last sector, +sectors or +size{K,M,G} (16777216-62914559, default 62914559):
Using default value 62914559
Partition 3 of type Linux and of size 22 GiB is set

Command (m for help): w
The partition table has been altered!

Calling ioctl() to re-read partition table.

WARNING: Re-reading the partition table failed with error 16: Device or resource busy.
The kernel still uses the old table. The new table will be used at
the next reboot or after you run partprobe(8) or kpartx(8)
Syncing disks.

# 更新内核的硬盘分区表信息
$ partprobe
----

== lvm

https://en.wikipedia.org/wiki/Logical_Volume_Manager_(Linux)[lvm^] 是 [.underline]##L##ogical [.underline]##V##olume [.underline]##M##anager 的缩写。

.常用命令如下：
[source%nowrap,bash]
----
# 查看物理卷
$ pvs
  PV         VG     Fmt  Attr PSize  PFree
  /dev/sda2  centos lvm2 a--  <7.00g    0

# 查看卷组
$ vgs
  VG     #PV #LV #SN Attr   VSize  VFree
  centos   1   2   0 wz--n- <7.00g    0

# 查看逻辑卷
$ lvs
  LV   VG     Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  root centos -wi-ao----  <6.20g
  swap centos -wi-ao---- 820.00m

# 创建物理卷
$ pvcreate /dev/sda3
  Physical volume "/dev/sda3" successfully created.

# 添加物理卷到卷组
$ vgextend centos /dev/sda3
  Volume group "centos" successfully extended

# 扩展逻辑卷，使用剩余的空间
$ lvextend -l +100%FREE /dev/centos/root
  Size of logical volume centos/root changed from <6.20 GiB (1586 extents) to 28.19 GiB (7217 extents).
  Logical volume centos/root successfully resized.

# 查看 / 可用空间
$ df -Th
文件系统                类型      容量  已用  可用 已用% 挂载点
devtmpfs                devtmpfs  4.8G     0  4.8G    0% /dev
tmpfs                   tmpfs     4.9G     0  4.9G    0% /dev/shm
tmpfs                   tmpfs     4.9G  8.7M  4.8G    1% /run
tmpfs                   tmpfs     4.9G     0  4.9G    0% /sys/fs/cgroup
/dev/mapper/centos-root xfs       6.2G  6.0G  193M   97% /
/dev/sda1               xfs      1014M  181M  834M   18% /boot
tmpfs                   tmpfs     984M     0  984M    0% /run/user/0

# 扩展文件系统空间，使用剩余空间
$ xfs_growfs /dev/centos/root
meta-data=/dev/mapper/centos-root isize=512    agcount=4, agsize=406016 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=0 spinodes=0
data     =                       bsize=4096   blocks=1624064, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
log      =internal               bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
data blocks changed from 1624064 to 7390208
----

== df

df 是 [.underline]##d##isk [.underline]##f##ree 的缩写，
指磁盘文件，用于查看文件系统磁盘空间使用情况。

本手册页记录了 df 的 GNU 版本。
df 显示文件系统上包含每个文件名参数的可用磁盘空间量。
如果未提供文件名，则会显示所有当前挂载的文件系统上的可用空间。
默认情况下，磁盘空间以 1K 块显示，除非设置了环境变量 POSIXLY_CORRECT，在这种情况下，将使用 512 字节块。
如果参数是包含已挂载文件系统的磁盘设备节点的绝对文件名，则 df 显示该文件系统上的可用空间，而不是包含设备节点的文件系统上的可用空间。
此版本的 df 无法显示未挂载文件系统上的可用空间，因为在大多数类型的系统上，这样做需要非常不可移植的文件系统结构的深入了解。

.常用命令如下：
[source%nowrap,bash]
----
$ df -hi
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 4.8G     0  4.8G   0% /dev
tmpfs                    4.9G     0  4.9G   0% /dev/shm
tmpfs                    4.9G  8.7M  4.8G   1% /run
tmpfs                    4.9G     0  4.9G   0% /sys/fs/cgroup
/dev/mapper/centos-root  6.2G  6.2G   49M 100% /
/dev/sda1               1014M  181M  834M  18% /boot
tmpfs                    984M     0  984M   0% /run/user/0
----

// /usr 目录发音是 user ，但实际它是 Unix System Resources

== du

[source%nowrap,bash]
----
# 查询前 10 个，磁盘空间占用最高的文件或目录
$ du -h / | sort -h -r | head -n 10

35G     /
28G     /var
20G     /var/log
8.4G    /var/lib
8.1G    /var/lib/docker
4.8G    /var/lib/docker/containers
4.7G    /usr
3.3G    /var/lib/docker/overlay2
2.3G    /var/lib/docker/containers/4cd6a41874de24ddde8b003b5a1a7f106697e30bc066168ab1085273eee26051
1.4G    /var/lib/docker/containers/b0dba1e87ee6cd6fbd3b0aaffb437451711aa9113894a4d751c6cebf5fd472f0
----



== 参考

* https://blog.csdn.net/xjp_xujiping/article/details/120076715[Linux 磁盘与分区命名^]
* https://unix.stackexchange.com/questions/412731/do-all-disks-devices-in-my-hw-machines-start-with-sd[Do all disks devices in my HW machines start with - sd?^]
* https://www.redhat.com/sysadmin/resize-lvm-simple[How to resize a logical volume with 5 simple LVM commands^]
